name: Cypress E2E Testing

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
           node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure all history is fetched so Cypress can access all files

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci  # This ensures dependencies are installed from package-lock.json

    - name: Run Cypress tests
      run: npx cypress run  # This will run the Cypress tests

    - name: List Cypress screenshots and videos
      run: |
        echo "Screenshots:"
        ls -R cypress/screenshots || echo "No screenshots"
        echo "Videos:"
        ls -R cypress/videos || echo "No videos"

    - name: Upload Cypress screenshots and videos
      uses: actions/upload-artifact@v3
      with:
        name: cypress-artifacts
        path: |
          cypress/screenshots/*
          cypress/videos/*
